name: Lint

on: 
  [push, pull] :
  branches: [ main ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npm run lint